url: https://kaanoguzhan.github.io

# Site settings
title: Kaan Oguzhan
email: kaan.oguzhan@tum.de
description: "Personal page for Kaan Oguzhan. A brief overview to my life and my projects == It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Postal address (add as many lines as necessary)
address:
  - line: Munchen, Germany

# Build settings
markdown: kramdown
permalink: pretty